name: 'Verify Commits Action'
description: 'GitHub Action to verify commit signatures'
author: 'Public Domain'
inputs:
  base_branch:
    description: 'The base branch to compare against'
    required: false
    default: 'main'
  file_path:
    description: 'The file path to check for modifications'
    required: false
  public_key_files:
    description: 'Multi-line input of paths to public key files'
    required: true
  commits:
    description: 'JSON-encoded array of commit SHAs (optional)'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
